#!/usr/bin/env bash
# =============================================================================
# act2-pr.sh — Act 2 Phase 2a: Commit worker, rebase onto FEEL commit, open PR
# =============================================================================
# Run this after: Claude Code has written worker/index.js AND commit 2 pushed
#                 (commit 2 = FEEL expression applied in Web Modeler + synced)
# Next script:    03-act2-fix.sh  (after CI failure is visible to the audience)
#
# What this does:
#   1. Commits Claude Code's worker file alongside the BPMN (which may have
#      drifted slightly from Web Modeler's last sync)
#   2. Rebases that commit on top of commit 2 so history reads:
#        commit 1 (skeleton) → commit 2 (FEEL mapping) → commit 3 (worker)
#   3. Pushes and opens a PR against the upstream fork
#
# Why rebase instead of merge: keeps the narrative linear — the worker commit
# arrives after the BA's FEEL mapping, matching the story told on stage.
#
# Why --repo HanselIdes/camunda-8-tutorials: gh defaults to the upstream
# camunda/camunda-8-tutorials. Always specify the fork explicitly.
# BRITTLE: Assumes Claude Code wrote index.js with a job type matching the
# BPMN process ID. If Web Modeler Copilot generated different task IDs or job
# types, the worker may poll the wrong job type and never complete. Verify:
#   grep -n "jobType\|activateJobs\|type" solutions/vehicle-lookup/worker/index.js
#   grep -n "zeebe:taskDefinition" solutions/vehicle-lookup/*.bpmn
# =============================================================================
set -euo pipefail

REPO="$(cd "$(dirname "$0")/../../.." && pwd)"
cd "$REPO"

git checkout web-modeler

# Discover BPMN filename dynamically — Web Modeler names it from the diagram title
BPMN_FILE=$(ls "solutions/vehicle-lookup/"*.bpmn | head -1)

echo "=== Staging worker + BPMN ==="
git add "solutions/vehicle-lookup/worker/index.js" "$BPMN_FILE"
git commit -m "feat: add vehicle risk assessment worker"

echo "=== Rebasing onto FEEL commit (commit 2) ==="
git fetch origin web-modeler
# Replay our worker commit on top of whatever Leila just pushed from Web Modeler
git rebase origin/web-modeler

# Sanity check: confirm output mappings from the FEEL expression survived the rebase
echo "Output mappings after rebase:"
grep -E "resultExpression|zeebe:output" "$BPMN_FILE" | head -10

git push origin web-modeler

echo ""
echo "=== Opening PR ==="
gh pr create \
  --title "Add vehicle-risk-assessment worker" \
  --body "Generated by Claude Code from $(basename "$BPMN_FILE"). Implements io.camunda.demo:vehicle-risk-assessment job type." \
  --base main \
  --head web-modeler \
  --repo HanselIdes/camunda-8-tutorials

echo ""
echo "=== PRESENTER: Switch to GitHub Actions tab. Show CI failure in ~20-30s. ==="
echo "=== Say: 'CI caught a variable drift: vehicleScore referenced in BPMN but not in variable schema.' ==="
echo ""
echo "When CI failure is visible, run: bash solutions/vehicle-lookup/demo/03-act2-fix.sh"
