#!/usr/bin/env bash
# Trigger: Claude Code done + FEEL expression applied + commit 2 pushed
# Does: stage worker, rebase onto FEEL commit, push, open PR
set -euo pipefail

REPO="$(cd "$(dirname "$0")/../../.." && pwd)"
cd "$REPO"

git checkout web-modeler

BPMN_FILE=$(ls "solutions/vehicle-lookup/"*.bpmn | head -1)

echo "=== Staging worker + BPMN ==="
git add "solutions/vehicle-lookup/worker/index.js" "$BPMN_FILE"
git commit -m "feat: add vehicle risk assessment worker"

echo "=== Rebasing onto FEEL commit (commit 2) ==="
git fetch origin web-modeler
git rebase origin/web-modeler

echo "Output mappings after rebase:"
grep -E "resultExpression|zeebe:output" "$BPMN_FILE" | head -10

git push origin web-modeler

echo ""
echo "=== Opening PR ==="
gh pr create \
  --title "Add vehicle-risk-assessment worker" \
  --body "Generated by Claude Code from $(basename "$BPMN_FILE"). Implements io.camunda.demo:vehicle-risk-assessment job type." \
  --base main \
  --head web-modeler \
  --repo HanselIdes/camunda-8-tutorials

echo ""
echo "=== PRESENTER: Switch to GitHub Actions tab. Show CI failure in ~20-30s. ==="
echo "=== Say: 'CI caught a variable drift: vehicleScore referenced in BPMN but not in variable schema.' ==="
echo ""
echo "When CI failure is visible, run: bash solutions/vehicle-lookup/demo/act2-fix.sh"
